import { useEffect, useRef } from 'react';

const KEY = 'rasira-scroll-y';

/** How long to keep trying before giving up. The page can only be restored
 * once it is tall enough, and that depends on a network fetch, so this has
 * to outlast a slow sheet response without hanging around forever. */
const RESTORE_BUDGET_MS = 3000;

/**
 * Keeps the homepage where you left it across a reload.
 *
 * The browser already does this, and it does it wrong here. Native scroll
 * restoration fires once, early — and at that moment the page is only a
 * hero tall, because the article grid is still waiting on the Google Sheet
 * fetch (see useArticles). A browser cannot scroll past the bottom of a
 * short document, so it clamps the restore to near zero and you land back
 * on the hero. Once the articles arrive the page grows, but nothing goes
 * back to finish the job.
 *
 * So: take restoration off the browser (scrollRestoration = 'manual') and
 * retry across frames until the target is actually reachable.
 */
export function useScrollRestoration(enabled: boolean) {
  // True while a restore is in flight. The save effect stands down for the
  // duration — otherwise the scroll events generated by our own restore
  // attempts would write the clamped position back over the target we are
  // still trying to reach.
  const restoringRef = useRef(false);

  useEffect(() => {
    if (!('scrollRestoration' in window.history)) return;
    const previous = window.history.scrollRestoration;
    window.history.scrollRestoration = 'manual';
    return () => {
      window.history.scrollRestoration = previous;
    };
  }, []);

  useEffect(() => {
    if (!enabled) return;

    let frame = 0;
    const save = () => {
      if (restoringRef.current || frame) return;
      frame = requestAnimationFrame(() => {
        frame = 0;
        sessionStorage.setItem(KEY, String(Math.round(window.scrollY)));
      });
    };

    window.addEventListener('scroll', save, { passive: true });
    // pagehide rather than beforeunload: it also fires when the page goes
    // into the back/forward cache, which beforeunload does not, and it is
    // the one of the two that works on iOS Safari.
    window.addEventListener('pagehide', save);

    return () => {
      if (frame) cancelAnimationFrame(frame);
      window.removeEventListener('scroll', save);
      window.removeEventListener('pagehide', save);
    };
  }, [enabled]);

  useEffect(() => {
    if (!enabled) return;

    // Read here rather than at render time so that RETURNING to the
    // homepage (from an article) picks up the position saved when leaving
    // it, not a stale one captured on first mount. Safe from the save
    // effect above despite that one registering first: it only writes on a
    // scroll event, and both effects run in the same synchronous flush, so
    // no event can interleave between them.
    const target = Number(sessionStorage.getItem(KEY) ?? 0);
    if (target <= 0) return;

    restoringRef.current = true;
    let cancelled = false;
    const startedAt = performance.now();

    // Any deliberate input abandons the restore. Without this, a user who
    // starts scrolling while the page is still growing would be yanked
    // back to the saved position on the next frame.
    const abandon = () => {
      cancelled = true;
      restoringRef.current = false;
    };
    window.addEventListener('wheel', abandon, { passive: true });
    window.addEventListener('touchstart', abandon, { passive: true });
    window.addEventListener('keydown', abandon);

    const step = () => {
      if (cancelled) return;
      // behavior:'instant' is required, not cosmetic — html carries
      // scroll-behavior:smooth (index.css), so a default scrollTo would
      // animate, and animating once per frame toward a moving target never
      // settles.
      window.scrollTo({ top: target, behavior: 'instant' });

      const reached = Math.abs(window.scrollY - target) <= 1;
      const expired = performance.now() - startedAt > RESTORE_BUDGET_MS;
      if (reached || expired) {
        restoringRef.current = false;
        return;
      }
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);

    return () => {
      cancelled = true;
      restoringRef.current = false;
      window.removeEventListener('wheel', abandon);
      window.removeEventListener('touchstart', abandon);
      window.removeEventListener('keydown', abandon);
    };
  }, [enabled]);
}
